version: "3.8"
services:
    zookeeper:
      container_name: zookeeper
      image: bitnami/zookeeper:latest
      ports:
        - 2181:2181
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
    kafka1:
      container_name: kafka1
      image: bitnami/kafka:latest
      ports:
        - '9093:9093'
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9093
        - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      depends_on:
        - zookeeper
    kafka2:
      container_name: kafka2
      image: bitnami/kafka:latest
      ports:
        - '9094:9094'
      environment:
        - KAFKA_BROKER_ID=2
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9092,EXTERNAL://localhost:9094
        - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      depends_on:
        - zookeeper
    kafka3:
      container_name: kafka3
      image: bitnami/kafka:latest
      ports:
        - '9095:9095'
      environment:
        - KAFKA_BROKER_ID=3
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9095
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:9092,EXTERNAL://localhost:9095
        - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      depends_on:
        - zookeeper
    kafdrop:
      container_name: kafdrop
      image: obsidiandynamics/kafdrop
      restart: "no"
      ports:
        - "9000:9000"
      environment:
        KAFKA_BROKERCONNECT: "CLIENT://kafka1:9092,CLIENT://kafka2:9092,CLIENT://kafka3:9092"
        JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
      depends_on:
        - "kafka1"
        - "kafka2"
        - "kafka3"